---
resources:
- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: git@github.com:yasmaryhd/concourse-bump-git-semver.git
    branch: version
    file: version
    private_key: ((git_ssh.private_key))

jobs:
- name: bump-version
  public: true
  serial: true
  plan:
  - get: version
    params: {bump: patch} #0.0.1 -> 0.0.2
  - put: version
    params: {file: version/version}
  - task: display-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: version
      run:
        path: cat
        args: [version/version]
